### ISSUE TITLE
[Views] Displaying data in a list

### ISSUE THREAD

**Issue by juwonleee** [juwonleee/DumLive#2]
## Section 1 ****Display a list of daily scrums****

- [ ] Step 1. Create a new SwiftUI View file named ScrumsView.swift.
- [ ] Step 2. Add a constant property named scrums of type [DailyScrum].
- [ ] Step 3. In ScrumsView_Previews, pass an array of scrums to the ScrumsView initializer.
- [ ] Step 4. Replace the default Text view with a List view. Pass the scrums array and a key path to the title property to the initializer.
- [ ] Step 5. Initialize a CardView in the List closure.
- [ ] Step 6. Set the background color of the row to scrum.theme.mainColor.

### Section 2 ****Make scrums identifiable****

- [ ] Step 1. Open DailyScrum.swift, and declare conformance to the Identifiable protocol.
- [ ] Step 2. Add a constant named id of type UUID.
- [ ] Step 3. Add an initializer that assigns a default value to the id property.
- [ ] Step 4. In ScrumsView.swift, remove the id parameter from the List initializer.
- [ ] Step 5. Open ScrumdingerApp.swift, and set ScrumsView as the initial view for the app. WindowGroup is one of the primitive scenes that SwiftUI provides. In iOS, the views you add to the WindowGroup scene builder are presented in a window that fills the device’s entire screen.
- [ ] Step 6. Build and run the app in Simulator to verify that ScrumsList appears when the app launches.

**Comment by jis00ya** [comment]
0613 덤덤스터디에서 완료 [Views] Displaying data in a list(#2)메시지로 완료
